# Generated by Django 4.2.2 on 2023-07-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='john.doe@gmail.com', max_length=200),
        ),
    ]
